title = "graveyard #42"
# Must be a valid UNIX file name
package = "graveyard_42"

[env]

	[env.dev]
	ips = ["192.168.1.1", "192.168.1.2"]
	domain = "dev.cats.com"
	admin = "admin@cats.com"
		[env.dev.ssh]
		# 22 by default
		port = 23
		# relative/absolute path to ssh key
		key = "dev_ssh_key"
		# blank('') by default
		password = ""
		# 'admin' by default
		user = "admin"

	[env.prod]
	ips = ["192.168.1.3", "192.168.1.4"]
	domain = "cats.com"
	admin = "admin@cats.com"
		[env.prod.ssh]
		port = 23
		key = "prod_ssh_key"
		password = ""
		user = "admin"

[provision]
command = """
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install
sudo apt-get install oracle-java8-installer
"""

[run]
# relative/absolute path to the local directory that contains the app to be deployed
directory = "deploy"
# command to start the app
start = "java -jar {path}/app.jar {path}/config-{env}.yml"
# (Optional) command to run after starting the app on each instance
complete = """
"""